#!/bin/sh

mvn archetype:generate -DarchetypeGroupId=name.jchein.portfolio.archetypes -DarchetypeArtifactId=command-side -DarchetypeVersion=0.0.1-SNAPSHOT -DgroupId=name.jchein.portfolio.microservices -DartifactId=customer.accounts  -Dversion=0.0.1-SNAPSHOT -DserviceName=customer.accounts -Dpackage=name.jchein.portfolio.microservices.customer.accounts -DschemaName=customer_accounts -DservicePath=customer/accounts
mvn archetype:generate -DarchetypeGroupId=name.jchein.portfolio.archetypes -DarchetypeArtifactId=command-side -DarchetypeVersion=0.0.1-SNAPSHOT -DgroupId=name.jchein.portfolio.microservices -DartifactId=order.payments  -Dversion=0.0.1-SNAPSHOT -DserviceName=order.payments -Dpackage=name.jchein.portfolio.microservices.order.payments -DschemaName=order_payments -DservicePath=order/payments
mvn archetype:generate -DarchetypeGroupId=name.jchein.portfolio.archetypes -DarchetypeArtifactId=command-side -DarchetypeVersion=0.0.1-SNAPSHOT -DgroupId=name.jchein.portfolio.microservices -DartifactId=pizzaops.delivery  -Dversion=0.0.1-SNAPSHOT -DserviceName=pizzaops.delivery -Dpackage=name.jchein.portfolio.microservices.pizzaops.delivery -DschemaName=pizzaops_delivery -DservicePath=pizzaops/delivery
mvn archetype:generate -DarchetypeGroupId=name.jchein.portfolio.archetypes -DarchetypeArtifactId=command-side -DarchetypeVersion=0.0.1-SNAPSHOT -DgroupId=name.jchein.portfolio.microservices -DartifactId=pizzaops.supplychain  -Dversion=0.0.1-SNAPSHOT -DserviceName=pizzaops.supplychain -Dpackage=name.jchein.portfolio.microservices.pizzaops.supplychain -DschemaName=pizzaops_supplychain -DservicePath=pizzaops/supplychain
mvn archetype:generate -DarchetypeGroupId=name.jchein.portfolio.archetypes -DarchetypeArtifactId=command-side -DarchetypeVersion=0.0.1-SNAPSHOT -DgroupId=name.jchein.portfolio.microservices -DartifactId=pizzaops.staffing  -Dversion=0.0.1-SNAPSHOT -DserviceName=pizzaops.staffing -Dpackage=name.jchein.portfolio.microservices.pizzaops.staffing -DschemaName=pizzaops_staffing -DservicePath=pizzaops/staffing
mvn archetype:generate -DarchetypeGroupId=name.jchein.portfolio.archetypes -DarchetypeArtifactId=command-side -DarchetypeVersion=0.0.1-SNAPSHOT -DgroupId=name.jchein.portfolio.microservices -DartifactId=pizzaops.fleet  -Dversion=0.0.1-SNAPSHOT -DserviceName=pizzaops.fleet -Dpackage=name.jchein.portfolio.microservices.pizzaops.fleet -DschemaName=pizzaops_fleet -DservicePath=pizzaops/fleet
mvn archetype:generate -DarchetypeGroupId=name.jchein.portfolio.archetypes -DarchetypeArtifactId=command-side -DarchetypeVersion=0.0.1-SNAPSHOT -DgroupId=name.jchein.portfolio.microservices -DartifactId=pizzaops.process  -Dversion=0.0.1-SNAPSHOT -DserviceName=pizzaops.process -Dpackage=name.jchein.portfolio.microservices.pizzaops.process -DschemaName=pizzaops_process -DservicePath=pizzaops/process
mvn archetype:generate -DarchetypeGroupId=name.jchein.portfolio.archetypes -DarchetypeArtifactId=command-side -DarchetypeVersion=0.0.1-SNAPSHOT -DgroupId=name.jchein.portfolio.microservices -DartifactId=employee.registry  -Dversion=0.0.1-SNAPSHOT -DserviceName=employee.registry -Dpackage=name.jchein.portfolio.microservices.employee.registry -DschemaName=employee_registry -DservicePath=employee/registry
mvn archetype:generate -DarchetypeGroupId=name.jchein.portfolio.archetypes -DarchetypeArtifactId=command-side -DarchetypeVersion=0.0.1-SNAPSHOT -DgroupId=name.jchein.portfolio.microservices -DartifactId=edge.delivery  -Dversion=0.0.1-SNAPSHOT -DserviceName=edge.delivery -Dpackage=name.jchein.portfolio.microservices.edge.delivery -DschemaName=edge_delivery -DservicePath=edge/delivery
mvn archetype:generate -DarchetypeGroupId=name.jchein.portfolio.archetypes -DarchetypeArtifactId=command-side -DarchetypeVersion=0.0.1-SNAPSHOT -DgroupId=name.jchein.portfolio.microservices -DartifactId=edge.kitchen  -Dversion=0.0.1-SNAPSHOT -DserviceName=edge.kitchen -Dpackage=name.jchein.portfolio.microservices.edge.kitchen -DschemaName=edge_kitchen -DservicePath=edge/kitchen
mvn archetype:generate -DarchetypeGroupId=name.jchein.portfolio.archetypes -DarchetypeArtifactId=command-side -DarchetypeVersion=0.0.1-SNAPSHOT -DgroupId=name.jchein.portfolio.microservices -DartifactId=edge.supply  -Dversion=0.0.1-SNAPSHOT -DserviceName=edge.supply -Dpackage=name.jchein.portfolio.microservices.edge.supply -DschemaName=edge_supply -DservicePath=edge/supply
mvn archetype:generate -DarchetypeGroupId=name.jchein.portfolio.archetypes -DarchetypeArtifactId=command-side -DarchetypeVersion=0.0.1-SNAPSHOT -DgroupId=name.jchein.portfolio.microservices -DartifactId=edge.shuttle  -Dversion=0.0.1-SNAPSHOT -DserviceName=edge.shuttle -Dpackage=name.jchein.portfolio.microservices.edge.shuttle -DschemaName=edge_shuttle -DservicePath=edge/shuttle

mvn archetype:generate -DarchetypeGroupId=name.jchein.portfolio.archetypes -DarchetypeArtifactId=query-side -DarchetypeVersion=0.0.1-SNAPSHOT -DgroupId=name.jchein.portfolio.microservices -DartifactId=reporting.dashboards  -Dversion=0.0.1-SNAPSHOT -DserviceName=reporting.dashboards -Dpackage=name.jchein.portfolio.microservices.reporting.dashboards -DschemaName=reporting_dashboards -DservicePath=reporting/dashboards
mvn archetype:generate -DarchetypeGroupId=name.jchein.portfolio.archetypes -DarchetypeArtifactId=query-side -DarchetypeVersion=0.0.1-SNAPSHOT -DgroupId=name.jchein.portfolio.microservices -DartifactId=reporting.predictions  -Dversion=0.0.1-SNAPSHOT -DserviceName=reporting.predictions -Dpackage=name.jchein.portfolio.microservices.reporting.predictions -DschemaName=reporting_predictions -DservicePath=reporting/predictions

mvn archetype:generate -DarchetypeGroupId=name.jchein.portfolio.archetypes -DarchetypeArtifactId=service-gateway -DarchetypeVersion=0.0.1-SNAPSHOT -DgroupId=name.jchein.portfolio.microservices -DartifactId=edge.potato  -Dversion=0.0.1-SNAPSHOT -DserviceName=edge.potato -Dpackage=name.jchein.portfolio.microservices.edge.potato -DschemaName=edge_potato -DservicePath=edge/potato

mvn archetype:generate -DarchetypeGroupId=name.jchein.portfolio.archetypes -DarchetypeArtifactId=command-side -DarchetypeVersion=0.0.1-SNAPSHOT -DgroupId=name.jchein.portfolio.microservices -DartifactId=edge.berry  -Dversion=0.0.1-SNAPSHOT -DserviceName=edge.berry -Dpackage=name.jchein.portfolio.microservices.edge.berry -DschemaName=edge_berry -DservicePath=edge/berry

mvn archetype:generate -DarchetypeGroupId=name.jchein.portfolio.archetypes -DarchetypeArtifactId=query-side -DarchetypeVersion=0.0.1-SNAPSHOT -DgroupId=name.jchein.portfolio.microservices -DartifactId=edge.juice  -Dversion=0.0.1-SNAPSHOT -DserviceName=edge.juice -Dpackage=name.jchein.portfolio.microservices.edge.juice -DschemaName=edge_juice -DservicePath=edge/juice

